# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

language: node_js
node_js:
  - '6'
  - 'stable'
cache: yarn

# Make Greenkeeper work with lockfiles:
# https://github.com/greenkeeperio/greenkeeper-lockfile/tree/f62f2f3e33cd1dd349c2898e0129c693cbc5804d#yarn
env:
  global:
    secure: m+tlzSiX8Dh5bx3T952QKCVvKvW9wwsO3lf7atFeydgKLWrbPC0zdoLiI/cM6WH3cjKXywme8kktL5UmDx/gsVcRlTgKecuSy1eQjQbV3pdTeXKjuLG3u4baReq1DOT2RwOihGccQ3Epdtlp7VXBzhlm8iQEWn/wHuYJsGrIRF0=

before_install:
# package-lock.json was introduced in npm@5
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
